spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    protocol:
    properties:
      mail:
        smtp:
          soketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
            auth: true
            starttls:
              enable: true
              connectiointimeout: 5000
              timeout: 3000
              writetimeout: 5000
    thymeleaf:
      enable: true
  envio:
    email:
      remetente:
        nomeRemetente: 'Giaccneto'
server:
  port: 8082